# Generated by Django 3.2.9 on 2021-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='性别')),
                ('school', models.CharField(max_length=20, verbose_name='学院')),
                ('class_name', models.CharField(max_length=20, verbose_name='班级')),
                ('class_position', models.CharField(max_length=20, verbose_name='班级职务')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('admission', models.DateTimeField(verbose_name='入学时间')),
            ],
        ),
    ]
